### PR TITLE
Database optimization

### PR DESCRIPTION
**Pull request by ghost**
For this exercise we have optimized the database we created for the veterinarian clinic, according to the following requirements:

    The following queries are taking too much time (1 sec = 1000ms can be considered as too much time for database query). Try them on your machine to confirm it:
        SELECT COUNT(*) FROM visits where animal_id = 4;
        SELECT * FROM visits where vet_id = 2;
        SELECT * FROM owners where email = 'owner_18327@mail.com';

    Use EXPLAIN ANALYZE on the previous queries to check what is happening. Take screenshots of them - they will be necessary later.

    Find a way to decrease the execution time of the first query. Look for hints in the previous lessons.

    Find a way to improve execution time of the other two queries.

    While you are making changes, check if they help by running EXPLAIN ANALYZE. Once you succeed, take a screenshot of the EXPLAIN ANALYZE result showing that time actually decreased.

    Any changes you made to your database schema should be added to the schema.sql file and commited in a new pull request.

    If you decide to commit any INSERT INTO queries - remember to add the to the data.sql file. It is important to keep only the queries that change the database structure in the schema.sql file.

1st query before optimization:
1st_query_before

1st query after optimization:
1st_query_after

2nd query before optimization:
2nd_query_before

2nd query after optimization:
2nd_query_after

3rd query before optimization:
3rd_query_before

3rd query after optimization:
3rd_query_after

    NOTE: once you are done with this task feel free to remove your database in order to free up some space on your computer. With database schema you will be able to re-create it at any point of time.

The screenshots are saved in the .docx file

### CODE REVIEW

**Review by mmsesay — COMMENTED** [review]
Hi @iKuartz & @Kakalanp & @41hulk, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a descriptive readme. Please see this [example](https://github.com/microverseinc/readme-template/blob/master/README.md).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by mmsesay — CHANGES_REQUESTED** [review]
Hi @Kakalanp & @iKuartz & @41hulk,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mmsesay** [comment]
You can also consider:
- [x] Try adding the screenshots of the `EXPLAIN ANALYZE` command in the PR description. Doing so will make it easier to show exactly what are the execution times before and after the improvement of the 3 select queries. Putting them in a doc file is good, but wasn't required.

```sql
SELECT COUNT(*) FROM visits where animal_id = 4;
SELECT * FROM visits where vet_id = 2;
SELECT * FROM owners where email = 'owner_18327@mail.com';
```
- [x] Also try adding `INDEX` for foreign keys in the visit and owners table. You only did it for the animal id.

**Comment by ghost** [comment]
> You can also consider:
> 
>     * [ ]  Try adding the screenshots of the `EXPLAIN ANALYZE` command in the PR description. Doing so will make it easier to show exactly what are the execution times before and after the improvement of the 3 select queries. Putting them in a doc file is good, but wasn't required.
> 
> 
> ```sql
> SELECT COUNT(*) FROM visits where animal_id = 4;
> SELECT * FROM visits where vet_id = 2;
> SELECT * FROM owners where email = 'owner_18327@mail.com';
> ```
> 
>     * [x]  Also try adding `INDEX` for foreign keys in the visit and owners table. You only did it for the animal id.

You are correct, we input the indexation commands, but forgot to add them to schema. We are also adding the screenshots now.

**Review by VICTOR-CHUKWU — APPROVED** [review]
Hi Team, 
# STATUS: APPROVED! 🥇 💯 
done

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
